name = "SeisPlot"
uuid = "00783350-183d-11e9-0ed7-9f3f45823183"
authors = ["fercarozzi <carozzi@ualberta.ca>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SeisMain = "5696fd22-15e8-11e9-1986-f9ab08703604"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
FFTW = "1"
Documenter = "0.27"
DocumenterTools = "0.1"
SeisMain = "0.1"
PyCall = "1"
PyPlot = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
